[project]
name = "mcp-server-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.9.4",
    "pydantic>=2.10.0,<3.0.0",
    "pydantic-settings>=2.0.0,<3.0.0",
]
